# -*- coding: utf-8 -*-
"""PalakBhootra_model_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lJrNUpP8fGdPZ7fSV8j_LtzjpwjnCr1R

Student Id: 100818888

Name: Palak Bhootra

Import packages
"""

import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score

"""Import dataset"""

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data'
names = ['id', 'clump_thickness', 'uniformity_of_cell_size', 'uniformity_of_cell_shape', 'marginal_adhesion', 'single_epithelial_cell_size', 'bare_nuclei', 'bland_chromatin', 'normal_nucleoli', 'mitoses', 'class']

df = pd.read_csv(url, names=names).replace('?', np.nan).dropna()
df.drop(['id'], axis=1, inplace=True)
df

print(df.describe())

"""Split dataset into training and testing"""

X = df.drop(['class'], axis=1).to_numpy()
y = df['class'].to_numpy()

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

"""Logistic Regression"""

logistic = LogisticRegression()
logistic.fit(x_train, y_train)
accuracy = accuracy_score(y_test,logistic.predict(x_test))
print('Accuracy is: ',accuracy)

"""Testing model"""

test = np.array([[4, 3, 1, 2, 2, 2, 3, 2, 10]])
test = test.reshape(len(test), -1)
prediction = logistic.predict(test)
print(prediction)

"""Decision Tree Classifier"""

dt_clf = DecisionTreeClassifier(max_leaf_nodes=10, random_state=0, criterion='entropy')
dt_clf.fit(x_train, y_train)
dt_clf_acc = accuracy_score(y_test,dt_clf.predict(x_test))
print('Accuracy is: ',dt_clf_acc)

"""Testing model"""

test = np.array([[4, 3, 1, 2, 2, 2, 3, 2, 10]])
test = test.reshape(len(test), -1)
prediction = logistic.predict(test)
print(prediction)